// Display
#define C8_HEIGHT_PIXELS 32
#define C8_WIDTH_PIXELS 64
#define C8_RESOLUTION_MULTIPLIER 10
#define C8_ACTUAL_WIDTH (C8_WIDTH_PIXELS * C8_RESOLUTION_MULTIPLIER)
#define C8_ACTUAL_HEIGHT (C8_HEIGHT_PIXELS * C8_RESOLUTION_MULTIPLIER)

// Memory
#define C8_RAM_SIZE 4096
#define C8_FONT_START_LOCATION 0x050
#define C8_PROGRAM_START_LOCATION 0x200

// Instructions
#define C8_INSTRUCTION_CLEAR_SCREEN 0x00
#define C8_INSTRUCTION_JUMP 0x01
#define C8_INSTRUCTION_VX_SET 0x06
#define C8_INSTRUCTION_VX_ADD 0x07
#define C8_INSTRUCTION_I_SET 0x0A
#define C8_INSTRUCTION_DRAW 0x0D